### PR TITLE
Fix log resolvers

### LINKED ISSUE #2: LibLog log resolution seems to be broken
When included in a project which is already using Log4Net, this library fails to discover that and simply throws an error about being unable to resolve SeriLog types.

From a brief investigation, it appears that the resolution logic has been disabled at some point. We need to light it up again.

### PR DESCRIPTION
**Pull request by vexx32**
Log resolution behaviour had been deliberately turned off at some point, which made this lib accidentally dependent on SeriLog.

Fix is to disable the overrides and comment out one of the provider registrations, which was throwing errors from its static constructor.

Fixes #2

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@vexx32 initially I was confused as to why we were bumping to 1.4.0, but then I saw your commit message, and I think that this makes sense.  Given that there hasn't been a new package version for a while now, I think we are ok to move forward with this, but we may want to discuss this further to decide how we guard against a potential collision in the future.

**Comment by gep13** [comment]
@vexx32 I do think it makes sense to create a milestone, and assign the issue to the milestone, so that we can track what is going into a new release.

Will leave the PR open until this is done, and then we can push out a new version.

**Comment by vexx32** [comment]
@gep13 all sorted! 👍

**Comment by gep13** [comment]
@vexx32 Thanks for getting that sorted out!

**Pull request merged**
