### PR TITLE
(#10) Update to the public recipe package

### PR DESCRIPTION
**Pull request by vexx32**
## Description Of Changes

- Updated to the public Chocolatey.Cake.Recipe package
- Removed the source configurations as we were setting the same
  as the defaults.
- Included some readme updates, that thing hasn't been updated in eons.

## Motivation and Context

- We forgot to come back and update the recipe package used in the previous PR.
- There were some README changes needed, that file was _very_ old and no longer useful to anyone.

## Testing

1. Build script run to ensure all tests are still passing and new build recipe functions properly.

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)

## Related Issue

#10

## Change Checklist

* [ ] Requires a change to the documentation
* [x] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Windos** [comment]
This _looks_ good to me, and build on the Dev server.

It did use the branch name as part of the version number, though I imagine this will be something that won't be accurately reflected until we're building from master (@gep13?)

**Review by Windos — APPROVED** [review]
This _looks_ good to me, and built on the Dev server.

It did use the branch name as part of the version number, though I imagine this will be something that won't be accurately reflected until we're building from master (@gep13 this was the same as one of the earlier Cake builds we looked at?)

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@vexx32 thanks for getting this updated, and thanks to @Windos for the review!

**Pull request merged**
